In [6]:
# Essential for numerical computing, providing powerful array objects and
# tools for mathematical operations, especially in scientific and
# technical computing
# Use Cases: Numerical simulations, data analysis, and mathematical modeling

import numpy as np

# Create sample data and save to file
sample_data = np.array([10, 20, 30, 40, 50])
np.save("data.npy", sample_data)

np_file = np.load("data.npy")  # Load data from a .npy file
np.save("output.npy", np_file)  # Save data to a .npy file

print(
    np.fromiter(range(5), dtype=int)
)  # Create a NumPy array from an iterable: array([0, 1, 2, 3, 4])
arr1d = np.array([1, 2, 3, 4, 5])  # Create a 1D NumPy array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  # Create a 2D NumPy array (matrix)
print(np.asarray(arr1d))  # Convert a list to a NumPy array: array([1, 2, 3, 4, 5])

# Array operations

print(arr1d + 10)  # Add 10 to each element: [11, 12, 13, 14, 15]
print(np.sum(arr1d))  # Sum of all elements: 15
print(np.dot(arr1d, arr1d))  # Dot product of arr1d with itself: 55
print(np.mean(arr1d))  # Mean of the array: 3.0
print(arr2d.reshape(3, 2))  # Reshape 2D array to 3x2: [[1, 2], [3, 4], [5, 6]]
print(arr2d.transpose())  # Transpose the 2D array: [[1, 4], [2, 5], [3, 6]]
print(arr1d[arr1d > 2])  # Filter elements greater than 2: [3, 4, 5]
print(np.sort(arr1d))  # Sort the array: [1, 2, 3, 4, 5]
print(np.unique(arr1d))  # Unique elements in the array: [1, 2, 3, 4, 5]
print(
    np.random.rand(3, 3)
)  # Create a 3x3 array of random numbers: [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]]
print(np.zeros((2, 3)))  # Create a 2x3 array of zeros: [[0, 0, 0], [0, 0, 0]]
print(np.ones((2, 4)))  # Create a 2x4 array of ones: [[1, 1, 1, 1], [1, 1, 1, 1]]
print(np.empty((3, 2)))  # Create a 3x2 empty array: uninitialized values
print(
    np.arange(0, 10, 2)
)  # Create an array with values from 0 to 10 with step 2: [0, 2, 4, 6, 8]
print(
    np.linspace(0, 1, 5)
)  # Create an array with 5 evenly spaced values between 0 and 1: [0.0, 0.25, 0.5, 0.75, 1.0]
print(np.sqrt(arr1d))  # Square root of each element: [1.0, 1.414, 1.732, 2.0, 2.236]
print(np.power(arr1d, 3))  # Raise each element to the power of 3: [1, 8, 27, 64, 125]
print(np.var(arr1d))  # Variance of the array: 2.0
print(np.std(arr1d))  # Standard deviation of the array: 1.414
print(np.min(arr1d))  # Minimum element in the array: 1
print(np.max(arr1d))  # Maximum element in the array: 5


[0 1 2 3 4]
[1 2 3 4 5]
[11 12 13 14 15]
15
55
3.0
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[[0.11847892 0.53775588 0.36531209]
 [0.66055393 0.64791347 0.15434108]
 [0.22635306 0.70101925 0.20851592]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
2.0
1.4142135623730951
1
5
